lightsoff, swell-foop: Don't try to manually iterate GLib main loop inside inner loop
Fix swell-foop and lightsoff not working due to:
TypeError Result of expression 'GLib.main_context_iteration' [undefined] is not a function.

Comment out the GLib.main_context_ functions. I don't know what if anything
these should be replaced with, but swell-foop and lightsoff appear to work
without them.